theme: jekyll-theme-cayman
title: Andrea Selva
description: Project Officer, data enthusiast (and something like a multipotential) based in Italy
<p align="center">
  <a href="https://www.linkedin.com/notifications/">LinkedIn</a> |
  <a href="https://twitter.com/andreaselva9">Twitter</a> |
  <a href="mailto:andrea.selva@outlook.it"> Contact me</a>
  <br><br>
  </p>
